api/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('api.views',
    url(r'^pic/', 'pic', name='pic'),
)

pam/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('pam.views',
    url(r'^pic/', 'pic', name='pic'),
    url(r'^aud/', 'aud', name='aud'),
    url(r'^mov/', 'mov', name='mov'),
)

pamjs/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pamjs.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    url(r'^$', 'pam.views.home', name='home'),

    url(r'^pam/', include('pam.urls', namespace='pam')),
    url(r'^api/', include('api.urls', namespace='api')),
)

urlpatterns += staticfiles_urlpatterns('static')

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.

pam/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import models
from pamjs.basemodels import CreateUpdateMixin
from django.utils.translation import ugettext_lazy as _, ugettext

import os
import time
import datetime


def upload_path(instance, old_filename):
    extension = os.path.splitext(old_filename)[1].lower()
    today = datetime.datetime.today()
    timestamp = str(time.time())
    file_path = 'pamjs/image/{year}{month}/{timestamp}{extension}'.format(
        year=today.year,
        month=today.month,
        timestamp=timestamp,
        extension=extension)
    return file_path


class ClassifyInfo(CreateUpdateMixin):
    classify = models.CharField(_('classify'), max_length=255, blank=True, null=True, help_text=u'资源分类')
    abbr = models.CharField(_('abbreviation'), max_length=255, blank=True, null=True, help_text=u'资源分类简称')
    status = models.BooleanField(_('status'), default=True, help_text=u'分类是否显示')
    priority = models.IntegerField(_('priority'), blank=True, null=True, help_text=u'分类展示的优先级')

    class Meta:
        verbose_name = _('classifyinfo')
        verbose_name_plural = _('classifyinfo')

    def __unicode__(self):
        return u'{0.classify}'.format(self)


class PictureInfo(CreateUpdateMixin):
    image = models.ImageField(_('image'), upload_to=upload_path, blank=True, null=True, help_text=u'图片上传')
    url = models.URLField(_('url'), blank=True, null=True, help_text=u'图片链接')
    info = models.TextField(_('info'), blank=True, null=True, help_text=u'图片描述信息')
    link = models.URLField(_('link'), blank=True, null=True, help_text=u'图片查看详情链接')
    md5 = models.CharField(_('md5'), max_length=255, blank=True, null=True, help_text=u'图片 hash 值')
    device = models.CharField(_('device'), max_length=255, blank=True, null=True, choices=settings.DEVICE_TYPE, help_text=u'图片适合的设备')
    classify = models.ForeignKey('ClassifyInfo', related_name='pic_classify', blank=True, null=True, help_text=u'图片所属分类')
    status = models.BooleanField(_('status'), default=True, help_text=u'图片是否显示')
    priority = models.IntegerField(_('priority'), blank=True, null=True, help_text=u'图片展示的优先级')

    class Meta:
        verbose_name = _('pictureinfo')
        verbose_name_plural = _('pictureinfo')

    def __unicode__(self):
        return u'{0.md5}'.format(self)

    def _data(self):
        return {
            'pk': self.pk,
            'image': settings.DOMAIN + self.image.url if self.image else self.url,
            'info': self.info,
            'link': self.link
        }

    data = property(_data)


class CacheInfo(CreateUpdateMixin):
    http_response = models.TextField(_('http_response'), blank=True, null=True, help_text=u'缓存的 HttpResponse')
    site = models.CharField(_('site'), max_length=255, blank=True, null=True, help_text=u'缓存站点')
    usr = models.CharField(_('usr'), max_length=255, blank=True, null=True, help_text=u'缓存用户')
    device = models.CharField(_('device'), max_length=255, blank=True, null=True, help_text=u'缓存设备')
    classify = models.CharField(_('classify'), max_length=255, blank=True, null=True, help_text=u'图片所属分类')
    cache_at = models.CharField(_('cache_at'), max_length=255, blank=True, null=True, help_text=u'缓存时间，精确到年月日')
    ip_addr = models.CharField(_('ip_addr'), max_length=255, blank=True, null=True, help_text=u'缓存 IP')

    class Meta:
        verbose_name = _('cacheinfo')
        verbose_name_plural = _('cacheinfo')

    def __unicode__(self):
        return u'{0.ip_addr}-{0.cache_at}'.format(self)

api/views.py
from django.shortcuts import render, HttpResponse

from pam.models import PictureInfo, CacheInfo

import json
import random
from datetime import datetime


def get_pic_httpresponse(callback, num, device, classify):
    pic_queryset = PictureInfo.objects.filter(status=True, device=device)
    if classify != '':
        pic_queryset = pic_queryset.filter(classify__abbr=classify)
    else:
        pass
    pic_queryset = random.sample(pic_queryset, num) if pic_queryset.count() > num else pic_queryset
    pic_list = [pic.data for pic in pic_queryset]

    return str(json.dumps(pic_list)) if callback == '' else callback + '([' + str(json.dumps(pic_list)) + '])'


def pic(request):
    site = request.GET.get('site', '')
    usr = request.GET.get('usr', '')
    num = int(request.GET.get('num', '5'))
    callback = request.GET.get('callback', '')
    cache = request.GET.get('cache', 'true')
    device = request.GET.get('device', 'C')
    classify = request.GET.get('classify', '')

    if cache == 'true':
        ip_addr = request.META['HTTP_X_FORWARDED_FOR'] if 'HTTP_X_FORWARDED_FOR' in request.META else request.META['REMOTE_ADDR']
        cache_at = datetime.today().strftime('%Y-%m-%d')
        hr, created = CacheInfo.objects.get_or_create(
            site=site,
            usr=usr,
            device=device,
            classify=classify,
            ip_addr=ip_addr,
            cache_at=cache_at,
            defaults={'http_response': get_pic_httpresponse(callback, num, device, classify)}
        )
        httpresponse = hr.http_response
    else:
        httpresponse = get_pic_httpresponse(callback, num, device, classify)

    return HttpResponse(httpresponse)

pam/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.shortcuts import render

from pam.form import PictureInfoModelForm
from pam.models import PictureInfo


def home(request):
    return render(request, 'pam/index.html')


def pic(request):
    form = PictureInfoModelForm()
    pic_list = PictureInfo.objects.filter(status=True)[:6]
    pic_list = [pic.data for pic in pic_list]

    if request.method == "POST":
        form = PictureInfoModelForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.status = True
            f.save()
            form = PictureInfoModelForm()

    return render(request, 'pam/p.html', dict(form=form, pics=pic_list))


def aud(request):
    return render(request, 'pam/a.html')


def mov(request):
    return render(request, 'pam/m.html')

pam/templates/pam/a.html
{% extends "base/pamjs_base.html" %}
{% load staticfiles %}

{% block content %}{% endblock %}

{% block script %}
    <script>
        (function () {
            var res = [
                "/static/pamjs/musics/qg",
                "/static/pamjs/musics/snq"
            ];
            PamJS._audio(0, res);
            // _audio(1, 1);
        })();
    </script>
{% endblock %}

pam/templates/pam/index.html
{% extends "base/pamjs_base.html" %}
{% load staticfiles %}

{% block script %}
    <script>
        (function () {
            var res = [
                {"image": "{% static 'pamjs/images/xjqxz5.jpg' %}", "info": "仙剑奇侠传 五", "link": "http://pal5.baiyou100.com/1701000.asp"},
                {"image": "{% static 'pamjs/images/yz.jpg' %}", "info": "乌尤尼盐湖", "link": "http://baike.baidu.com/view/185098.htm"},
            ]
            PamJS._bg(0, res, 10000);

            var res = [
                "{% static 'pamjs/musics/qg' %}",
                "{% static 'pamjs/musics/snq' %}"
            ];
            PamJS._audio(0, res);
        })();
    </script>
{% endblock %}

pam/templates/pam/m.html
{% extends "base/pamjs_base.html" %}
{% load staticfiles %}

{% block content %}{% endblock %}

{% block script %}
    <script>
        (function () {
            var res = [ "/static/pamjs/movies/movie" ];
            PamJS._movie(0, res);
            // _movie(1, 1);
        })();
    </script>
{% endblock %}

pam/templates/pam/p.html
{% extends "base/pamjs_base.html" %}
{% load staticfiles %}

{% block content %}
    <div>
        <table cellpadding="0" cellspacing="5" border="0" width="100%">
            <tbody>
                <tr>
                    <td class="cell leftPosition">
                        <span class="pamFont">
                            使用Local图片，直接调用_bg，参数1为本地的标识(0-Local，1-Server)，参数2为存放本地图片路径的数组，参数3为图片替换的间隔时间，单位：ms(如果参数2数组长度为1，则参数3随意，pam.js中不检查)
                        </span>
                        <div>
                            <code> </code>
                        </div>
                        <div>
                            <code>var res = ["images/xjqxz5.jpg", "images/gif.gif"];</code>
                        </div>
                        <div>
                            <code>_bg(0, res, 10000);</code>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td class="cell leftPosition">
                        <span class="pamFont">
                            使用Server图片，直接调用_bg，参数1为Server的标识(0-Local，1-Server)，参数2为单播还是组播的标识(0-单，1-组)，参数3为图片替换的间隔时间，单位：ms(如果参数2为0，则参数3随意，pam.js中不检查)
                        </span>
                        <div>
                            <code>_bg(1, 1, 10000);</code>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="cell-div">
        <form class="form-horizontal" method="post" action="{% url 'pam:pic' %}" enctype='multipart/form-data'>{% csrf_token %}

            <div>
                {% for err in form.non_field_errors %}
                    {{ err }}
                {% endfor %}
            </div>

            <table cellpadding="5" cellspacing="0" border="0" width="50%">
                <tbody>
                    <tr>
                        <td width="120" align="right">背景图片</td>
                        <td width="auto" align="left">{{ form.image }}</td>
                    </tr>
                    <tr>
                        <td width="120" align="right">图片链接</td>
                        <td width="auto" align="left">{{ form.url }}</td>
                    </tr>
                    <tr>
                        <td width="120" align="right">图片描述</td>
                        <td width="auto" align="left">{{ form.info }}</td>
                    </tr>
                    <tr>
                        <td width="120" align="right">跳转链接</td>
                        <td width="auto" align="left">{{ form.link }}</td>
                    </tr>
                    <tr>
                        <td width="120" align="right">所属分类</td>
                        <td width="auto" align="left">{{ form.classify }}</td>
                    </tr>
                    <tr>
                        <td width="120" align="right">适合设备</td>
                        <td width="auto" align="left">{{ form.device }}</td>
                    </tr>
                    <tr>
                        <td width="120" align="right"></td>
                        <td width="auto" align="left"><button type="submit" class="btn btn-control">上传</button></td>
                    </tr>
                </tbody>
            </table>

        </form>
    </div>

    <div class="cell-div">
        <table cellpadding="0" cellspacing="5" border="0" width="100%">
            <tbody>
                <tr>
                    {% for p in pics %}
                        <td class="cell-pic hvcenter"><a href="javascript:void(0)" class="pamFont"> <img src="{{ p.image }}" class="cell-pic hvcenter"></a></td>
                        {% if forloop.counter|divisibleby:3 %}</tr><tr>{% endif %}
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

{% block script %}
    <script>
        (function () {
            /*one method
            var path = "http://121.199.46.162/work/pam/background/";
            var ymd = new Date().pattern("yyyy-MM-dd");
            var res = [ path + "background-" + ymd + ".jpg" ];*/

            /*var newConfig = $.extend(config, {
                display: true;
            })*/

            PamJS.init({display: true, slide_image_classify: 'dw'})
            PamJS._bg(1, 1, 10000);
        })();
    </script>
{% endblock %}

pamjs/templates/base/pamjs_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>PamJs -- Pictures/Audios/Movies Operation for Humans</title>
        <link rel=stylesheet type=text/css href="{% static 'pamjs/css/pam.css' %}">
        <link rel=stylesheet type=text/css href="{% static 'pamjs/css/pamDemo.css' %}">
        <script type="text/javascript" src="{% static 'pamjs/js/pam.js' %}"></script>
    </head>

    <body>
        <div id="Div" class="Div">
            <div class="wapper">
                <center>
                    <div>
                        <h1><a href="{% url 'home' %}" class="pamFont">欢迎使用pam.js</a></h1>
                        <h3><span class="pamFont">PamJs -- Pictures/Audios/Movies Operation for Humans</span></h3>
                    </div>

                    {% block content %}{% endblock %}

                    <div>
                        <table cellpadding="0" cellspacing="5" border="0" width="100%">
                            <tbody>
                                <tr>
                                    <td width="33%" class="cell hvcenter" onclick="location.href={% url 'pam:pic' %};"><a href="{% url 'pam:pic' %}" class="pamFont"> 背景图片(Pictures) </a></td>
                                    <td width="33%" class="cell hvcenter" onclick="location.href={% url 'pam:aud' %};"><a href="{% url 'pam:aud' %}" class="pamFont"> 背景音乐(Audios) </a></td>
                                    <td width="*%" class="cell hvcenter" onclick="location.href={% url 'pam:mov' %};"><a href="{% url 'pam:mov' %}" class="pamFont"> 背景视频(Movies) </a></td>
                                </tr>
                                <tr>
                                    <td class="cell hvcenter"><a href="javascript:void(0)" class="pamFont"> 浮层展示(FloatLayer) </a></td>
                                    <td class="cell hvcenter"><a href="javascript:void(0)" class="pamFont"> 轮播图(Lunbotu) </a></td>
                                    <td class="cell hvcenter"><a href="javascript:void(0)" class="pamFont"> 即将开放(Coming Soon) </a></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div>
                        <img id="fler" src="{% static 'pamjs/images/13Y4K9Lkrd9rCxHnF8b3axUKbjtA3ZWF1d.png' %}" alt="" class="img img-well img-polaroid img-hover" onclick="javascript:showid('floatLayer', document.getElementById('fler').src, '比特币捐助钱包');">
                    </div>
                    <div id="floatLayer" class="floatLayer" style="display:none;"></div>
                </center>
            </div>
        </div>

        {% block script %}{% endblock %}
    </body>
</html>